SRC= Warlock.cpp ASpell.cpp ATarget.cpp Fwoosh.cpp Dummy.cpp Fireball.cpp Polymorph.cpp BrickWall.cpp SpellBook.cpp TargetGenerator.cpp main.cpp

NAME=c02

CC= clang++ -Wall -Werror -Wextra 

$(NAME):
	$(CC) $(SRC) -o $(NAME)

fclean:
	rm -f $(NAME)

re: fclean $(NAME)


